use_frameworks!

platform :ios, '8.0'

target 'HIHttpTool_Example' do
  pod 'HIHttpTool', :path => '../'

  target 'HIHttpTool_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
